// Mocks generated by Mockito 5.4.6 from annotations
// in portafolio/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i3;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i5;
import 'package:flutter/foundation.dart' as _i7;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:portafolio/app/data/http/http.dart' as _i13;
import 'package:portafolio/app/data/services/remote/account_api.dart' as _i12;
import 'package:portafolio/app/data/services/remote/authentication_api.dart'
    as _i8;
import 'package:portafolio/app/data/services/remote/categories_service.dart'
    as _i21;
import 'package:portafolio/app/data/services/remote/internet_checker.dart'
    as _i6;
import 'package:portafolio/app/data/services/remote/movies_service.dart'
    as _i19;
import 'package:portafolio/app/data/services/remote/performers_service.dart'
    as _i17;
import 'package:portafolio/app/data/services/remote/person_service.dart'
    as _i22;
import 'package:portafolio/app/data/services/remote/trending_service.dart'
    as _i16;
import 'package:portafolio/app/domain/either/either.dart' as _i9;
import 'package:portafolio/app/domain/enums.dart' as _i10;
import 'package:portafolio/app/domain/models/movie.dart' as _i15;
import 'package:portafolio/app/domain/models/movie_detail.dart' as _i20;
import 'package:portafolio/app/domain/models/performer.dart' as _i18;
import 'package:portafolio/app/domain/models/person_detail.dart' as _i23;
import 'package:portafolio/app/domain/models/user.dart' as _i14;
import 'package:portafolio/app/domain/repositories/authentication_repository.dart'
    as _i24;
import 'package:portafolio/app/domain/repositories/categories_repository.dart'
    as _i27;
import 'package:portafolio/app/domain/repositories/performers_repository.dart'
    as _i26;
import 'package:portafolio/app/domain/repositories/trending_repository.dart'
    as _i25;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIOSOptions_0 extends _i1.SmartFake implements _i2.IOSOptions {
  _FakeIOSOptions_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_1 extends _i1.SmartFake
    implements _i2.AndroidOptions {
  _FakeAndroidOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_2 extends _i1.SmartFake implements _i2.LinuxOptions {
  _FakeLinuxOptions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_3 extends _i1.SmartFake
    implements _i2.WindowsOptions {
  _FakeWindowsOptions_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_4 extends _i1.SmartFake implements _i2.WebOptions {
  _FakeWebOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMacOsOptions_5 extends _i1.SmartFake implements _i2.MacOsOptions {
  _FakeMacOsOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i3.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i4.Stream<List<_i5.ConnectivityResult>>.empty(),
      ) as _i4.Stream<List<_i5.ConnectivityResult>>);

  @override
  _i4.Future<List<_i5.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ConnectivityResult>>.value(
            <_i5.ConnectivityResult>[]),
      ) as _i4.Future<List<_i5.ConnectivityResult>>);
}

/// A class which mocks [InternetChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetChecker extends _i1.Mock implements _i6.InternetChecker {
  MockInternetChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> hasInternet() => (super.noSuchMethod(
        Invocation.method(
          #hasInternet,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i2.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_0(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i2.IOSOptions);

  @override
  _i2.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_1(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i2.AndroidOptions);

  @override
  _i2.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_2(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i2.LinuxOptions);

  @override
  _i2.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_3(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i2.WindowsOptions);

  @override
  _i2.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_4(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i2.WebOptions);

  @override
  _i2.MacOsOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeMacOsOptions_5(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i2.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i7.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterListener({
    required String? key,
    required _i7.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterAllListenersForKey,
          [],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
        Invocation.method(
          #unregisterAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> write({
    required String? key,
    required String? value,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> read({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> containsKey({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> delete({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String>> readAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<void> deleteAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isCupertinoProtectedDataAvailable,
          [],
        ),
        returnValue: _i4.Future<bool?>.value(),
      ) as _i4.Future<bool?>);
}

/// A class which mocks [AuthenticationAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationAPI extends _i1.Mock implements _i8.AuthenticationAPI {
  MockAuthenticationAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i10.SignInFailure, String>> createRequestToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #createRequestToken,
          [],
        ),
        returnValue: _i4.Future<_i9.Either<_i10.SignInFailure, String>>.value(
            _i11.dummyValue<_i9.Either<_i10.SignInFailure, String>>(
          this,
          Invocation.method(
            #createRequestToken,
            [],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i10.SignInFailure, String>>);

  @override
  _i4.Future<_i9.Either<_i10.SignInFailure, String>> createSessionWithLogin({
    required String? username,
    required String? password,
    required String? requestToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSessionWithLogin,
          [],
          {
            #username: username,
            #password: password,
            #requestToken: requestToken,
          },
        ),
        returnValue: _i4.Future<_i9.Either<_i10.SignInFailure, String>>.value(
            _i11.dummyValue<_i9.Either<_i10.SignInFailure, String>>(
          this,
          Invocation.method(
            #createSessionWithLogin,
            [],
            {
              #username: username,
              #password: password,
              #requestToken: requestToken,
            },
          ),
        )),
      ) as _i4.Future<_i9.Either<_i10.SignInFailure, String>>);

  @override
  _i4.Future<_i9.Either<_i10.SignInFailure, String>> createSession(
          String? requestToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [requestToken],
        ),
        returnValue: _i4.Future<_i9.Either<_i10.SignInFailure, String>>.value(
            _i11.dummyValue<_i9.Either<_i10.SignInFailure, String>>(
          this,
          Invocation.method(
            #createSession,
            [requestToken],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i10.SignInFailure, String>>);
}

/// A class which mocks [AccountAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountAPI extends _i1.Mock implements _i12.AccountAPI {
  MockAccountAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i13.HttpFailure, _i14.User>> getAccount(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [sessionId],
        ),
        returnValue: _i4.Future<_i9.Either<_i13.HttpFailure, _i14.User>>.value(
            _i11.dummyValue<_i9.Either<_i13.HttpFailure, _i14.User>>(
          this,
          Invocation.method(
            #getAccount,
            [sessionId],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i13.HttpFailure, _i14.User>>);

  @override
  _i4.Future<_i9.Either<_i13.HttpFailure, List<_i15.Movie>>> getFavorites({
    required int? accountId,
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
          {
            #accountId: accountId,
            #sessionId: sessionId,
          },
        ),
        returnValue:
            _i4.Future<_i9.Either<_i13.HttpFailure, List<_i15.Movie>>>.value(
                _i11.dummyValue<_i9.Either<_i13.HttpFailure, List<_i15.Movie>>>(
          this,
          Invocation.method(
            #getFavorites,
            [],
            {
              #accountId: accountId,
              #sessionId: sessionId,
            },
          ),
        )),
      ) as _i4.Future<_i9.Either<_i13.HttpFailure, List<_i15.Movie>>>);

  @override
  _i4.Future<_i9.Either<_i13.HttpFailure, bool>> markAsFavorite({
    required int? accountId,
    required String? sessionId,
    required int? movieId,
    required bool? favorite,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsFavorite,
          [],
          {
            #accountId: accountId,
            #sessionId: sessionId,
            #movieId: movieId,
            #favorite: favorite,
          },
        ),
        returnValue: _i4.Future<_i9.Either<_i13.HttpFailure, bool>>.value(
            _i11.dummyValue<_i9.Either<_i13.HttpFailure, bool>>(
          this,
          Invocation.method(
            #markAsFavorite,
            [],
            {
              #accountId: accountId,
              #sessionId: sessionId,
              #movieId: movieId,
              #favorite: favorite,
            },
          ),
        )),
      ) as _i4.Future<_i9.Either<_i13.HttpFailure, bool>>);
}

/// A class which mocks [TrendingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrendingService extends _i1.Mock implements _i16.TrendingService {
  MockTrendingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i13.HttpFailure, List<_i15.Movie>>> getMovies(
          _i10.TimeWindow? timeWindow) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovies,
          [timeWindow],
        ),
        returnValue:
            _i4.Future<_i9.Either<_i13.HttpFailure, List<_i15.Movie>>>.value(
                _i11.dummyValue<_i9.Either<_i13.HttpFailure, List<_i15.Movie>>>(
          this,
          Invocation.method(
            #getMovies,
            [timeWindow],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i13.HttpFailure, List<_i15.Movie>>>);
}

/// A class which mocks [PerformersService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerformersService extends _i1.Mock implements _i17.PerformersService {
  MockPerformersService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i13.HttpFailure, List<_i18.Performer>>> getPerformers(
          _i10.TimeWindow? timeWindow) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformers,
          [timeWindow],
        ),
        returnValue: _i4
            .Future<_i9.Either<_i13.HttpFailure, List<_i18.Performer>>>.value(
            _i11.dummyValue<_i9.Either<_i13.HttpFailure, List<_i18.Performer>>>(
          this,
          Invocation.method(
            #getPerformers,
            [timeWindow],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i13.HttpFailure, List<_i18.Performer>>>);
}

/// A class which mocks [MoviesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesService extends _i1.Mock implements _i19.MoviesService {
  MockMoviesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i13.HttpFailure, _i20.MovieDetail>> getById(
    int? id, {
    String? sessionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
          {#sessionId: sessionId},
        ),
        returnValue:
            _i4.Future<_i9.Either<_i13.HttpFailure, _i20.MovieDetail>>.value(
                _i11.dummyValue<_i9.Either<_i13.HttpFailure, _i20.MovieDetail>>(
          this,
          Invocation.method(
            #getById,
            [id],
            {#sessionId: sessionId},
          ),
        )),
      ) as _i4.Future<_i9.Either<_i13.HttpFailure, _i20.MovieDetail>>);
}

/// A class which mocks [CategoriesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesService extends _i1.Mock implements _i21.CategoriesService {
  MockCategoriesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i9.Either<_i13.HttpFailure,
          ({List<_i15.Movie> movies, int page, int totalPages})>> getMovies(
    _i10.MovieCategory? category, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovies,
          [category],
          {#page: page},
        ),
        returnValue: _i4.Future<
            _i9.Either<
                _i13.HttpFailure,
                ({
                  List<_i15.Movie> movies,
                  int page,
                  int totalPages
                })>>.value(_i11.dummyValue<
            _i9.Either<_i13.HttpFailure,
                ({List<_i15.Movie> movies, int page, int totalPages})>>(
          this,
          Invocation.method(
            #getMovies,
            [category],
            {#page: page},
          ),
        )),
      ) as _i4.Future<
          _i9.Either<_i13.HttpFailure,
              ({List<_i15.Movie> movies, int page, int totalPages})>>);
}

/// A class which mocks [PersonService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonService extends _i1.Mock implements _i22.PersonService {
  MockPersonService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i13.HttpFailure, _i23.PersonDetail>> getById(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4
            .Future<_i9.Either<_i13.HttpFailure, _i23.PersonDetail>>.value(
            _i11.dummyValue<_i9.Either<_i13.HttpFailure, _i23.PersonDetail>>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i13.HttpFailure, _i23.PersonDetail>>);
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i24.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i14.User?> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i4.Future<_i14.User?>.value(),
      ) as _i4.Future<_i14.User?>);

  @override
  _i4.Future<_i9.Either<_i10.SignInFailure, _i14.User>> signIn(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            username,
            password,
          ],
        ),
        returnValue:
            _i4.Future<_i9.Either<_i10.SignInFailure, _i14.User>>.value(
                _i11.dummyValue<_i9.Either<_i10.SignInFailure, _i14.User>>(
          this,
          Invocation.method(
            #signIn,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i10.SignInFailure, _i14.User>>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [TrendingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrendingRepository extends _i1.Mock
    implements _i25.TrendingRepository {
  MockTrendingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i10.HttpFailureType, List<_i15.Movie>>> getMovies(
          _i10.TimeWindow? timeWindow) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovies,
          [timeWindow],
        ),
        returnValue: _i4
            .Future<_i9.Either<_i10.HttpFailureType, List<_i15.Movie>>>.value(
            _i11.dummyValue<_i9.Either<_i10.HttpFailureType, List<_i15.Movie>>>(
          this,
          Invocation.method(
            #getMovies,
            [timeWindow],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i10.HttpFailureType, List<_i15.Movie>>>);
}

/// A class which mocks [PerformersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerformersRepository extends _i1.Mock
    implements _i26.PerformersRepository {
  MockPerformersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i9.Either<_i10.HttpFailureType, List<_i18.Performer>>> getPerformers(
          _i10.TimeWindow? timeWindow) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformers,
          [timeWindow],
        ),
        returnValue: _i4.Future<
                _i9.Either<_i10.HttpFailureType, List<_i18.Performer>>>.value(
            _i11.dummyValue<
                _i9.Either<_i10.HttpFailureType, List<_i18.Performer>>>(
          this,
          Invocation.method(
            #getPerformers,
            [timeWindow],
          ),
        )),
      ) as _i4.Future<_i9.Either<_i10.HttpFailureType, List<_i18.Performer>>>);
}

/// A class which mocks [CategoriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesRepository extends _i1.Mock
    implements _i27.CategoriesRepository {
  MockCategoriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i9.Either<_i10.HttpFailureType,
          ({List<_i15.Movie> movies, int page, int totalPages})>> getMovies(
    _i10.MovieCategory? category, {
    int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovies,
          [category],
          {#page: page},
        ),
        returnValue: _i4.Future<
            _i9.Either<
                _i10.HttpFailureType,
                ({
                  List<_i15.Movie> movies,
                  int page,
                  int totalPages
                })>>.value(_i11.dummyValue<
            _i9.Either<_i10.HttpFailureType,
                ({List<_i15.Movie> movies, int page, int totalPages})>>(
          this,
          Invocation.method(
            #getMovies,
            [category],
            {#page: page},
          ),
        )),
      ) as _i4.Future<
          _i9.Either<_i10.HttpFailureType,
              ({List<_i15.Movie> movies, int page, int totalPages})>>);
}
